version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - ./vols/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq.env
    networks:
      - internal

  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 27000
    networks:
      - internal
    ports:
      - "27000:27000"

  facer-ai:
    container_name: facer-ai
    build:
      context: ./facer-ai
      target: facer-ai
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ./vols/storage:/ai/data
    expose:
      - 40069
    ports:
      - "5000:40069"

  facer-api-gateway:
    container_name: facer-api-gateway
    build:
      context: ./facer-api
      dockerfile: ./apps/gateway/Dockerfile
      target: dev
    env_file:
      - ./facer-api/libs/common/.env
    command: npm run start:dev gateway
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./facer-api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '9000:40070'
    expose:
      - 40070
    networks:
      - internal

  facer-api-auth:
    container_name: facer-api-auth
    build:
      context: ./facer-api
      dockerfile: ./apps/auth/Dockerfile
      target: dev
    env_file:
      - ./facer-api/libs/common/.env
    command: npm run start:dev auth
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./facer-api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal

  facer-api-metrics:
    container_name: facer-api-metrics
    build:
      context: ./facer-api
      dockerfile: ./apps/metrics/Dockerfile
      target: dev
    env_file:
      - ./facer-api/libs/common/.env
    command: npm run start:dev metrics
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./facer-api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal

  facer-api-user:
    container_name: facer-api-user
    build:
      context: ./facer-api
      dockerfile: ./apps/user/Dockerfile
      target: dev
    env_file:
      - ./facer-api/libs/common/.env
    command: npm run start:dev user
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./facer-api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal

  facer-api-client:
    container_name: facer-api-client
    build:
      context: ./facer-api
      dockerfile: ./apps/client/Dockerfile
      target: dev
    env_file:
      - ./facer-api/libs/common/.env
    command: npm run start:dev client
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./facer-api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal

  facer-api-file:
    container_name: facer-api-file
    command: npm run start:dev file
    build:
      context: ./facer-api
      dockerfile: ./apps/file/Dockerfile
      target: dev
    env_file:
      - ./facer-api/libs/common/.env
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./facer-api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal
    

networks:
  internal:
    driver: bridge